# Generated by Django 3.1.2 on 2021-01-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('about', models.TextField(max_length=2500)),
            ],
        ),
        migrations.AlterField(
            model_name='verse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartPage.author'),
        ),
    ]
