# Generated by Django 3.1.2 on 2021-01-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartPage', '0002_auto_20210104_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='author',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
