# Generated by Django 3.1.2 on 2021-01-11 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StartPage', '0003_auto_20210109_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='author',
            name='width_field',
        ),
        migrations.AddField(
            model_name='verse',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
